feat: add post-install script, split install into smaller scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,15 +9,15 @@ set -o nounset
 set -o pipefail
 
 log_info() {
-  echo "[INFO]: $*"
+  printf "[INFO]: %s\n" "$*"
 }
 
 log_warn() {
-  echo "[WARN]: $*"
+  printf "[WARN]: %s\n" "$*" >&2
 }
 
 log_error() {
-  echo "[ERROR]: $*"
+  printf "[ERROR]: %s\n" "$*" >&2
 }
 
 CURRENT_SCRIPT_PATH="$(
@@ -53,46 +53,8 @@ case "${OSTYPE}" in
     ;;
 esac
 
-#
-# Link dotfiles
-#
+"${CURRENT_SCRIPT_PATH}/link-dotfiles"
 
-packages=(
-  "ag"
-  "alacritty"
-  "asdf"
-  "bin"
-  "emacs"
-  "git"
-  "gpg"
-  "haskell"
-  "javascript"
-  "ssh"
-  "tmux"
-  "nvim"
-  "yubikey"
-  "zsh"
-)
-
-case "${OSTYPE}" in
-  linux*)
-    :
-    packages+=(
-      "gammastep"
-      "sway"
-      "zeal"
-    )
-    ;;
-esac
-
-if command -v stow > /dev/null 2>&1; then
-  log_info "Symlinking dotfiles into $HOME..."
-  for pkg in "${packages[@]}"; do
-    pushd "${CURRENT_SCRIPT_PATH}/packages" > /dev/null
-    stow --target="$HOME" --verbose=1 "${pkg}"
-    popd > /dev/null
-  done
-  log_info "Symlinked dotfiles into $HOME."
-else
-  log_warn "stow not installed. Skipping dotfiles symlinking..."
-fi
+printf "====================\n"
+printf "Installation complete. You should now reboot and run \`./post-install\`.\n"
+printf "====================\n"
