feat: add flatpaks

diff --git a/linux/fedora-silverblue/flatpaks b/linux/fedora-silverblue/flatpaks
--- a/linux/fedora-silverblue/flatpaks
+++ b/linux/fedora-silverblue/flatpaks
@@ -9,40 +9,45 @@ flatpak remote-add --if-not-exists tuple https://dl.tuple.app/repo/stable
 flatpak remote-add --if-not-exists kdeapps https://distribute.kde.org/kdeapps.flatpakrepo
 
 packages=(
-  "flathub com.bitwarden.desktop"
-  "flathub com.discordapp.Discord"
-  "flathub com.github.iwalton3.jellyfin-media-player"
-  "flathub com.github.tchx84.Flatseal"
-  "flathub com.nextcloud.desktopclient.nextcloud"
-  "flathub com.rawtherapee.RawTherapee"
-  "flathub com.slack.Slack"
-  "flathub com.spotify.Client"
-  "flathub com.valvesoftware.Steam"
-  "flathub io.github.mimbrero.WhatsAppDesktop"
-  "flathub io.mpv.Mpv"
-  "flathub org.chromium.Chromium"
-  "flathub org.gimp.GIMP"
-  "flathub org.gnome.Boxes"
-  "flathub org.gnome.Calculator"
-  "flathub org.gnome.FileRoller"
-  "flathub org.gnome.FontManager"
-  "flathub org.gnome.gedit"
-  "flathub org.libreoffice.LibreOffice"
-  "flathub org.mozilla.Thunderbird"
-  "flathub org.musicbrainz.Picard"
-  "kdeapps org.kde.xwaylandvideobridge"
-  "tuple app.tuple.app"
+	"flathub com.bitwarden.desktop"
+	"flathub com.cassidyjames.butler"
+	"flathub com.discordapp.Discord"
+	"flathub com.github.iwalton3.jellyfin-media-player"
+	"flathub com.github.tchx84.Flatseal"
+	"flathub com.nextcloud.desktopclient.nextcloud"
+	"flathub com.rawtherapee.RawTherapee"
+	"flathub com.slack.Slack"
+	"flathub com.spotify.Client"
+	"flathub com.valvesoftware.Steam"
+	"flathub io.github.TransmissionRemoteGtk"
+	"flathub io.github.mimbrero.WhatsAppDesktop"
+	"flathub io.github.seadve.Kooha"
+	"flathub io.mpv.Mpv"
+	"flathub org.chromium.Chromium"
+	"flathub org.gimp.GIMP"
+	"flathub org.gnome.Boxes"
+	"flathub org.gnome.Calculator"
+	"flathub org.gnome.DejaDup"
+	"flathub org.gnome.FileRoller"
+	"flathub org.gnome.FontManager"
+	"flathub org.gnome.gedit"
+	"flathub org.libreoffice.LibreOffice"
+	"flathub org.mozilla.Thunderbird"
+	"flathub org.musicbrainz.Picard"
+	"flathub org.virt_manager.virt-viewer"
+	"kdeapps org.kde.xwaylandvideobridge"
+	"tuple app.tuple.app"
 )
 
-if ! command -v flatpak > /dev/null 2>&1; then
-  echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
-  exit 1
+if ! command -v flatpak >/dev/null 2>&1; then
+	echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
+	exit 1
 fi
 
 for package in "${packages[@]}"; do
-  # Split repository name / package name
-  # shellcheck disable=SC2086
-  flatpak install -y $package
+	# Split repository name / package name
+	# shellcheck disable=SC2086
+	flatpak install -y $package
 done
 
 flatpak permission-set flatpak background app.tuple.app yes
