refactor(arch): detect required bins in packages/flatpak scripts

diff --git a/linux/arch/flatpaks b/linux/arch/flatpaks
--- a/linux/arch/flatpaks
+++ b/linux/arch/flatpaks
@@ -31,6 +31,11 @@ packages=(
   "flathub org.zealdocs.Zeal"
 )
 
+if ! command -v flatpak > /dev/null 2>&1; then
+  echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
+  exit 1
+fi
+
 for package in "${packages[@]}"; do
   # Split repository name / package name
   # shellcheck disable=SC2086
diff --git a/linux/arch/packages b/linux/arch/packages
--- a/linux/arch/packages
+++ b/linux/arch/packages
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
+if ! command -v yay > /dev/null 2>&1; then
+  echo "ERROR: Could not find \`yay\`. Please install yay and re-run this script."
+  exit 1
+fi
+
 packages=(
   #
   # Base System
@@ -222,4 +231,6 @@ packages=(
   unzip
 )
 
+# Split array elements into individual package names
+# shellcheck disable=SC2068
 yay -S ${packages[@]}
